### ISSUE TITLE
never resets class

### ISSUE THREAD

**Issue by G2G2G2G** [Ara225/mini-frontend-projects#1]
https://github.com/Ara225/mini-frontend-projects/blob/master/2-bootstrap-modal-without-jQuery/bootstrap-modal-without-jQuery.html

you're just appending classes, resulting in something like:
```
class="modal fadeshowmodal fadeshowmodal fademodal fadeshowshowmodal fademodal fadeshowmodal fademodal fadeshowshowshowmodal fademodal fadeshowmodal fademodal fadeshowshowmodal fademodal fadeshowmodal fademodal fadeshowshowshowshowmodal fademodal fadeshowmodal fademodal fadeshowshowmodal fademodal fadeshowmodal fademodal fadeshowshowshowmodal fademodal fadeshowmodal fademodal fadeshowshowmodal fademodal fadeshowmodal fademodal fadeshowshowshowshow"
```
after a few clicks, gets worse and worse. One of the byproducts of += and not using simpler built in things like classList.remove/add

**Comment by Ara225** [comment]
Thanks for pointing this out. Will look at fixing it.
